version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full:0.12.6
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8000:8000"
    environment:
      - SERVICES=s3,iam,lambda,sqs,dynamodb,ssm,kms
      - DEBUG=1
      - START_WEB=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8000
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack/tmp
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"